# Generated by Django 5.1 on 2024-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='name',
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_en',
            field=models.CharField(default='test', max_length=100, unique=True, verbose_name='Name (En)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_ru',
            field=models.CharField(default='test', max_length=100, unique=True, verbose_name='Name (Ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_uz',
            field=models.CharField(default='test', max_length=100, unique=True, verbose_name='Name (Uz)'),
            preserve_default=False,
        ),
    ]
