from .constants import LanguageChoices

messages = {
    'greeting': '😊 Assalomu alaykum! Shifo24 botiga xush kelibsiz./\nWelcome to Shifo24 bot.',
    'select the language': "👇 Iltimos, tilni tanlang: /\nChoose a language :",
    'uzbek': "🇺🇿 O'zbek",
    'english': "🇺🇸 English",
    'russian': "🇷🇺 Русский",
    "selected language doesn't exist": "👇 Please choose from one of the available languages below:",

    'person emoji': '👤',
    'step emoji': '👣',
    'warning emoji': '⚠️',
    'condition emoji': '🛠',
    'next emoji': '⏭',
    'true icon': '✅',
    'false icon': '❌',
    'approved': '✅ Approved',
    'rejected': '❌ Rejected',
    'yes': "✅ Yes",
    'no': "❌ No",

    LanguageChoices.UZBEK: {
        'language flag': '🇺🇿',
        'main menu': '⏏️ Asosiy menu',
        'back button': '⬅️ Ortga',
        'skip button': "O'tkazib yuborish ➡",
        'continue button': "Davom etish ➡",
        'cancel button': '❌ Bekor qilish',
        'saved your language': 'Language saved, now we will talk using this language',
        'exception message': "🤕 Kechirasiz botimizda bir oz nosozlik yuzaga keldi.",
        'press one button': "Tugmalardan birini bosing",
        'change language': "Tilni o'zgartirish",
    },
    LanguageChoices.ENGLISH: {
        'language flag': '🇺🇸',
        'main menu': '⏏️ Main menu',
        'back button': '⬅️ Back',
        'skip button': 'Skip ➡',
        'continue button': "Davom etish ➡",
        'cancel button': '❌ Cancel',
        'saved your language': 'The chosen language has been saved.',
        'exception message': "🤕 I apologize for the inconvenience, but it seems like there was a minor malfunction in the bot.",
        'press one button': "Press one of the buttons",
        'change language': 'Change language',
    },
    LanguageChoices.RUSSIAN: {
        'language flag': '🇷🇺',
        'main menu': '⏏️ Main menu',
        'back button': '⬅️ Back',
        'skip button': 'Skip ➡',
        'continue button': "Davom etish ➡",
        'cancel button': '❌ Cancel',
        'saved your language': 'The chosen language has been saved.',
        'exception message': "🤕 I apologize for the inconvenience, but it seems like there was a minor malfunction in the bot.",
        'press one button': "Press one of the buttons",
        'change language': 'Change language',
    },
}
