from .constants import LanguageChoices

messages = {
    'greeting': '😊 Assalomu alaykum!\nShifo24 botiga xush kelibsiz. /\nWelcome to Shifo24 bot.',
    'select the language': "👇 Iltimos, tilni tanlang: /\nChoose a language :",
    'uzbek': "🇺🇿 O'zbek",
    'english': "🇺🇸 English",
    'russian': "🇷🇺 Русский",
    "selected language doesn't exist": "👇 Please choose from one of the available languages below:",

    'person emoji': '👤',
    'step emoji': '👣',
    'warning emoji': '⚠️',
    'condition emoji': '🛠',
    'next emoji': '⏭',
    'true icon': '✅',
    'false icon': '❌',
    'approved': '✅ Approved',
    'rejected': '❌ Rejected',
    'yes': "✅ Yes",
    'no': "❌ No",

    LanguageChoices.UZBEK: {
        'language flag': '🇺🇿',
        'main menu': '⏏️ Asosiy menu',
        'settings': '⚙️ Sozlamalar',
        'back button': '⬅️ Ortga',
        'skip button': "O'tkazib yuborish ➡",
        'continue button': "Davom etish ➡",
        'cancel button': '❌ Bekor qilish',
        "saved": "✅ Saved",
        'saved your language': '✅ Tanlangan til saqlandi.',
        'exception message': "🤕 Kechirasiz botimizda bir oz nosozlik yuzaga keldi.",
        'press one button': "Tugmalardan birini bosing",
        'change language': "Tilni o'zgartirish",
        "send number button": "📞 Telefon raqamni yuborish",
        "change number button": "📞 Telefon raqamni o'zgartirish",
        "enter phone number or click button": "<b>📞 Telefon raqamni yuborish</b> ni bosing yoki raqamingizni kiriting. Misol: <i>+998901234567</i>",
        "enter correct phone number": "Iltimos telefon raqamingizni to'g'ri formatda kiriting. Misol: <i>+998901234567</i>",
        "your phone number": "Sizning telefon raqamingiz: <b>{}</b>",
        "guide": "ℹ️ Siz ushbu bot orqali istalgan mutaxassislikdagi shifokorni osongina topishingiz va qabuliga yozilishingiz mumkin",
    },
    LanguageChoices.ENGLISH: {
        'language flag': '🇺🇸',
        'main menu': '⏏️ Main menu',
        'settings': '⚙️ Settings',
        'back button': '⬅️ Back',
        'skip button': 'Skip ➡',
        'continue button': "Davom etish ➡",
        'cancel button': '❌ Cancel',
        "saved": "✅ Saved",
        'saved your language': '✅ The chosen language has been saved.',
        'exception message': "🤕 I apologize for the inconvenience, but it seems like there was a minor malfunction in the bot.",
        'press one button': "Press one of the buttons",
        'change language': 'Change language',
        "send number button": "📞 Send number",
        "change number button": "📞 Change number",
        "enter phone number or click button": "<b>📞 Telefon raqamni yuborish</b> ni bosing yoki raqamingizni kiriting. Misol: <i>+998901234567</i>",
        "enter correct phone number": "Iltimos telefon raqamingizni to'g'ri formatda kiriting. Misol: <i>+998901234567</i>",
        "your phone number": "Sizning telefon raqamingiz: <b>{}</b>",
        "guide": "ℹ️ You can easily find a doctor specializing in any field and schedule an appointment using this bot.",
    },
    LanguageChoices.RUSSIAN: {
        'language flag': '🇷🇺',
        'main menu': '⏏️ Main menu',
        'settings': '⚙️ Settings',
        'back button': '⬅️ Back',
        'skip button': 'Skip ➡',
        'continue button': "Davom etish ➡",
        'cancel button': '❌ Cancel',
        "saved": "✅ Saved",
        'saved your language': '✅ The chosen language has been saved.',
        'exception message': "🤕 I apologize for the inconvenience, but it seems like there was a minor malfunction in the bot.",
        'press one button': "Press one of the buttons",
        'change language': 'Change language',
        "send number button": "📞 Send number",
        "change number button": "📞 Change number",
        "enter phone number or click button": "<b>📞 Telefon raqamni yuborish</b> ni bosing yoki raqamingizni kiriting. Misol: <i>+998901234567</i>",
        "enter correct phone number": "Iltimos telefon raqamingizni to'g'ri formatda kiriting. Misol: <i>+998901234567</i>",
        "your phone number": "Sizning telefon raqamingiz: <b>{}</b>",
        "guide": "ℹ️ С помощью этого чат-бота вы можете легко найти врача, специализирующегося в любой области, и записаться на прием.",

    },
}
