# Generated by Django 5.1 on 2024-08-29 16:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('order', '0002_alter_order_options_alter_order_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2024, 8, 29, 21, 17, 39, 189865))], verbose_name='Scheduled date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='specialization',
            field=models.ForeignKey(limit_choices_to={'children__isnull': True, 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='common.specialization', verbose_name='Specialization'),
        ),
    ]
