# Generated by Django 5.1 on 2024-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Scheduled date'),
        ),
    ]
