# Generated by Django 5.1 on 2024-09-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_status_alter_rate_doctor_and_more'),
        ('order', '0004_alter_order_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='doctors.doctor', verbose_name='Doctor'),
        ),
    ]
