# Generated by Django 5.1 on 2024-08-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specializations',
        ),
    ]
