# Generated by Django 5.1 on 2024-08-30 14:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramuser_step'),
        ('doctors', '0003_rename_specialization_doctor_specializations'),
        ('order', '0004_alter_order_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rate')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='doctors.doctor', verbose_name='Doctor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='order.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='bot.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'unique_together': {('doctor', 'user', 'order')},
            },
        ),
    ]
