# Generated by Django 5.1 on 2024-09-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_rate_doctor_alter_rate_order_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='doctors.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, verbose_name='Day'),
        ),
    ]
