# Generated by Django 5.1 on 2024-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
